spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spirng_batch_study
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB53Dialect
    open-in-view: true

  batch:
    job:
      names: ${job.name:NONE}

logging:
  level:
    root: info
    com.example.springbatchstudy: debug